selenium:
  driver_path: path/to/chromedriver

debug:
  logging_level: 3
  test_mode: true

app:
  timeout: 10
  alert_type: mp3
  bb_email: your bestbuy account email
  bb_password: your bestbuy account password
  bb_cvv: your bestbuy account card cvv
  amz_email: your amazon account email
  amz_pwd: your amazon account pwd
  queue_exists: true

available:
  timeout: 10
  open_new_browser: false
  short_url: true
  alert_type: mp3
  items:
    - name: "Magic: The Gathering Fantasy Collector Booster"
      link: https://www.amazon.com/Magic-Gathering-Fantasy-Collector-Booster/dp/B0DTN5HJD5?ref_=ast_sto_dp
      type: card
      auto_buy: false
    - name: "Magic: The Gathering Fantasy Collectors Commander"
      link: https://www.amazon.com/Magic-Gathering-Fantasy-Collectors-Commander/dp/B0DTMRCY7J?ref_=ast_sto_dp
      type: card
      auto_buy: false
    - name: "NVIDIA GeForce RTX 5090"
      link: https://www.bestbuy.com/site/nvidia-geforce-rtx-5090-32gb-gddr7-graphics-card-dark-gun-metal/6614151.p?skuId=6614151
      type: graphics_card
      auto_buy: false